-- DropIndex
DROP INDEX "price_rules_price_list_id_category_id_min_quantity_key";

-- AlterTable
ALTER TABLE "category_stock_logs" ADD COLUMN     "variant_id" TEXT;

-- AlterTable
ALTER TABLE "price_rules" ADD COLUMN     "variant_id" TEXT;

-- AlterTable
ALTER TABLE "product_items" ADD COLUMN     "variant_id" TEXT;

-- AlterTable
ALTER TABLE "sale_items" ADD COLUMN     "variant_id" TEXT,
ADD COLUMN     "variant_label" TEXT;

-- AlterTable
ALTER TABLE "sale_return_items" ADD COLUMN     "variant_id" TEXT;

-- CreateTable
CREATE TABLE "product_variants" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "category_id" TEXT NOT NULL,
    "attributes" JSONB NOT NULL DEFAULT '{}',
    "label" TEXT NOT NULL,
    "sku" TEXT NOT NULL,
    "barcode" TEXT,
    "price_override" DECIMAL(15,2),
    "quantity_on_hand" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "image_url" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "product_variants_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "product_variants_tenant_id_idx" ON "product_variants"("tenant_id");

-- CreateIndex
CREATE INDEX "product_variants_tenant_id_category_id_idx" ON "product_variants"("tenant_id", "category_id");

-- CreateIndex
CREATE INDEX "product_variants_tenant_id_category_id_is_active_idx" ON "product_variants"("tenant_id", "category_id", "is_active");

-- CreateIndex
CREATE INDEX "product_variants_tenant_id_barcode_idx" ON "product_variants"("tenant_id", "barcode");

-- CreateIndex
CREATE UNIQUE INDEX "product_variants_tenant_id_sku_key" ON "product_variants"("tenant_id", "sku");

-- CreateIndex
CREATE UNIQUE INDEX "product_variants_tenant_id_barcode_key" ON "product_variants"("tenant_id", "barcode") WHERE (barcode IS NOT NULL);

-- CreateIndex
CREATE INDEX "category_stock_logs_tenant_id_category_id_variant_id_idx" ON "category_stock_logs"("tenant_id", "category_id", "variant_id");

-- CreateIndex
CREATE INDEX "price_rules_price_list_id_category_id_variant_id_idx" ON "price_rules"("price_list_id", "category_id", "variant_id");

-- CreateIndex
CREATE INDEX "product_items_tenant_id_category_id_variant_id_stock_status_idx" ON "product_items"("tenant_id", "category_id", "variant_id", "stock_status");

-- CreateIndex
CREATE INDEX "product_items_tenant_id_category_id_variant_id_inventory_st_idx" ON "product_items"("tenant_id", "category_id", "variant_id", "inventory_status");

-- CreateIndex
CREATE INDEX "sale_items_variant_id_idx" ON "sale_items"("variant_id");

-- CreateIndex
CREATE INDEX "sale_return_items_variant_id_idx" ON "sale_return_items"("variant_id");

-- AddForeignKey
ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "inventory_categories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_items" ADD CONSTRAINT "product_items_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "category_stock_logs" ADD CONSTRAINT "category_stock_logs_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sale_items" ADD CONSTRAINT "sale_items_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sale_return_items" ADD CONSTRAINT "sale_return_items_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "price_rules" ADD CONSTRAINT "price_rules_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- HAND-APPENDED: not expressible in schema.prisma.
--
-- Everything above was generated by `prisma migrate diff` from schema.prisma.
-- This block is the one part Prisma cannot express, verified against 7.8.0:
-- `@@unique(..., nullsNotDistinct: true)` is rejected with "No such argument".
--
-- Why it matters: Postgres's default is NULLS DISTINCT, so without this a
-- product-level rule (variant_id IS NULL) could be inserted twice at the same
-- minQuantity tier. The 6-tier cascade in priceResolutionService.ts would then
-- pick an arbitrary winner between two equally-valid rows, and which one you
-- got would depend on row order. NULLS NOT DISTINCT treats the NULLs as equal,
-- which is exactly the intent: one product-level rule per tier, plus one rule
-- per variant per tier.
--
-- The DropIndex for price_rules_price_list_id_category_id_min_quantity_key is
-- above, in Prisma's generated output -- this replaces it, widened by
-- variant_id. Verified before applying: zero existing rows violate it.
--
-- Constraint name is deliberately short. The conventional
-- price_rules_price_list_id_category_id_variant_id_min_quantity_key is 65
-- characters, past Postgres's 63-byte identifier limit, and would have been
-- silently truncated to something no one could predict or grep for.
--
-- NOTE FOR FUTURE MIGRATIONS: schema.prisma declares no @@unique on PriceRule,
-- so Prisma does not know this constraint exists. Check `prisma migrate diff`
-- output for a DROP against it before applying any future migration.
ALTER TABLE "price_rules" ADD CONSTRAINT "price_rules_list_cat_variant_qty_key"
  UNIQUE NULLS NOT DISTINCT ("price_list_id", "category_id", "variant_id", "min_quantity");
